packages:
  - '@css'
  - '@cypress'
  - '@dsa'
  - '@expressjs'
  - '@html'
  - '@javascript'
  - '@jest'
  - '@logics'
  - '@markdown'
  - '@mobx'
  - '@mongodb'
  - '@mui'
  - '@nextjs'
  - '@nodejs'
  - '@puppeteer'
  - '@reactjs'
  - '@redux'
  - '@rollup'
  - '@routers'
  - '@sass'
  - '@storybook'
  - '@styledcomponents'
  - '@typescript'
  - '@webpack'